[package]
name = "netTest"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "server"
path = "src/server.rs"
# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[[bin]]
name = "client"
path = "src/client.rs"

[dependencies]
